In [1]:
import numpy as np

In [2]:
a = np.array([6,7,8])
b = np.array([5,-4,3])
c = np.array([5,-4,3,2])


In [3]:
a+b

array([11,  3, 11])

In [4]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
a-b

array([ 1, 11,  5])

In [6]:
a-c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [7]:
a*5

array([30, 35, 40])

In [8]:
a*b

array([ 30, -28,  24])